const dev = {
  BackendApiURL: process.env.BACKEND_API_URL,
  BackendPlaceholderApiURL: process.env.BACKEND_API_PLACEHOLDER_URL,
  LoginURL: process.env.LOGINURL,
  ADFSLoginURL: process.env.ADFS_LOGIN_URL,
  GoogleLoginURL: process.env.GOOGLE_LOGIN_URL,
  AdfsLogoutURL: process.env.ADFS_LOGOUT_URL,
  LogoutURL: process.env.LOGOUT_URL,
  imageBaseUrl: process.env.IMAGE_BASE_URL,
  downloadTemplateURL:'import-placeholder/SampleTemplate.xlsx',
  downloadIndexTemplateURL:'import-index/SampleIndexTemplate.xlsx',
  sampleVideoUidTemplateURL:'import-index/SampleVideoUidTemplate.xlsx',
  bulkPublishStatus: "/bulkOperations/Publish/status",
  episodePlaceholderList:"/episode/placeholder/re-generate",
  axinomCmsStatus: "/axinomCmsStatus",
  ingestionCmsStatus: "/ingestionCmsStatus",
  downloadJson:"downloadJson",
  defaultLanguageCode: "en",
  property:"property",
  castCrew:"castAndCrew",
  usersUrl: '/user',
  userLogout:'/user/logout',
  rolesUrl: '/roles',
  roleUrl: '/rolesFilter',
  masterUrl: '/master',
  masterTags: '/master/Tags',
  metaDataUrl: "/metadata",
  tagMasterGetUrl:"/master/Tags",
  masterContentSubType : "/master/EpisodeSubType",
  masterReasonType: "/master/ReasonType",
  masterLicenceTemplate : "/master/LicenceTemplate",
  metadata: '/metadata',
  createfaqUrl: '/faq',
  createProfileUrl: '/cast',
  archiveCastAndCrew: "",
  restoreCastAndCrew: "",
  castAndCrew: '/movie/castAndCrew',
  castnamesUrl: "/cast-names",
  moviesListUrl: '/movies',
  preSignedUrl: '/common/preSignedUrl',
  imageListing: '/cast/image',
  postphotoDetails: 'cast/image',
  editPhotoDetails: '/cast/image',
  deletePhotoDetails: '/cast/image',
  castList: '/cast-list',
  commonContentInfo: '/common/contentInfo',
  movieList: '/movie/list',
  movieDefaultListImage:'/movie/defaultListImage',
  videoDefaultListImage:'/video/defaultListImage',
  tvShowDefaultListImage:'/tvshow/defaultListImage',
  movieJourneyType: "/movie/journeytype",
  movieDetails: '/movie/details',
  movieTranslation: '/movie/translation',
  movieTranslationCastCrew: '/movie/castTranslation',
  movie: '/movie',
  movieClone: '/movie/clone',
  movieListTotal: '/movie/listTotal',
  videoList: '/video',
  videoListTotal: '/video/listTotal',
  videoClone: '/video/clone',
  movieVideoTranscoding: '/movie/video/transcoding',
  archive: '/movie/archive',
  restore: '/movie/draft/restore',
  linkList: '/movie/linklist',
  movieImageSet: '/movie/imageSet',
  collectionImageSet: '/collection/imageSet',
  movieProperties: '/movie/properties',
  videoProperties: '/video/properties',
  movieControlFields:'movie/properties/controlFields',
  mapContent: '/movie/mapContent',
  videoMapContent: '/video/mapContent',
  mapContentList:'movie/mapContentList',
  videoMapContentList:'video/mapContentList',
  mapContentRearrange: '/movie/mapContent/rearrange',
  relatedContent: '/movie/relatedContent',
  relatedContentRearrange: '/movie/relatedContent/rearrange',
  rearrangeContent: '/movie/rearrangeContent',
  collectionAssignment: '/movie/collectionAssign',
  checkList: '/movie/checklist',
  seoDetailsUrl: '/movie/seo',
  castChecklist: '/cast-action',
  castIsDoneUrl: '/cast/isDone',
  collectionIsDoneUrl: '/collection/action',
  castActionUrl: "/cast-action",
  imageMaxSize: 20000000,
  imageSizeError: `“Size of the File is incorrect“ Please upload the image between 0MB to 20MB for image.`,
  imageFormatError: `"Image file format is incorrect“ Please upload again"`,
  imageMarkAsDone: '/cast/isDone',
  imageReorderUrl: '/cast/image/reorder',
  createEditVideo: '/movie/video',
  videoLock: '/movie/videolock',
  createVideoDetails: 'details',
  imageLockedUrl: '/cast/image/isLocked',
  licenceModule: 'movie/licence',
  collection: '/collection',
  collectionListTotal:'/collection/listTotal',
  languageListUrl: '/movie/languageList',
  licenseCountries: '/movie/licenseCountries',
  workflowAPI: '/workflow',
  workflowHistory: '/workflow/history',
  languageListStatus: '/movie/languageListStatus',
  castLanguageListUrl: '/cast/LanguageList',
  castLanguageListStatus: '/cast/languageListStatus',
  collectionLanguageListStatus: '/collection/languageListStatus',
  updateSchedule:"/workflow/schedule/edit",
  movieLanguageListUrl: '/movie/isDoneList',
  collectionLanguageListUrl: '/collection/languageList',
  castWorkflow: '/workflow',
  castDeleteWorkflow: '/workflow/schedule',
  collectionProperties: '/collection/properties',
  collectionPropertiesControlFields: "/collection/properties/controlFields",
  collectionLicenseCountry:"/collection/licenseCountries",
  collectionSeo: '/collection/seo',
  collectionLicence: '/collection/licence',
  collectionAction: "/collection/action",
  assignAssets: '/collection/assignAsset',
  assignAssetsRearrange: '/collection/assignAsset/rearrange',
  assignAssetsRearrangeContent: '/collection/rearrangeContent',
  collectionTranslation: '/collection/translation',
  tvShowsList: 'tvShow',
  episodeList:'episode',
  episodegenerateXML: 'episode/createXML',
  tvshowSeason: '/tvShow/season',
  tvShow: {
    journeyType: "/tvshow/journeytype",
    edit: "/tvshow/edit",
    shows: '/tvShow/tvshow',
    count: '/tvShow/Count',
    action: '/tvShow/action',
    imageSet: "/shows/imageSet",
    languageListStatus: '/tvShow/languageListStatus',
    licenseCountries: '/tvShow/licenseCountries',
    collectionAssignment: '/tvShow/collectionAssign',
    relatedContent: '/tvShow/relatedContent',
    relatedRearrangeContent: '/tvShow/rearrangeContent',
    seo: '/tvShow/seo',
    translation: 'tvShow/translation',
    translationCastCrew: '/tvShow/castTranslation',
    globalTranslation: '/tvShow/globalTranslation',
    mapContent: "/tvshow/mapContent",
    mapContentRearrange: '/tvshow/mapContent/rearrange',
    global: '/tvShow/global',
  },
  tvShowProperties: '/tvShow/properties',
  tvShowGlobalFiels: '/tvShow/global',
  tvShowControlFields:'tvshow/properties/controlFields',
  seasonControlFields:'season/properties/controlFields',
  seasonEpisodeStatus:"/tvShow/seasonEpisodeStatus",
  tvShowDetails: 'tvShow/details',
  tvShowCastAndCrew: 'tvShow/castAndCrew',
  tvShowImageSet: "/tvShow/imageSet",
  tvShowMapContent: '/tvShow/MapContent',
  tvShowList: '/tvShow',
  tvshowClone: '/tvShow/clone',
  seasonClone: '/season/clone',
  episodeClone: '/episode/clone',
  episodeXmlStatus:'/episode/get-episode-xml-status',
  episodePrefixCheck: '/episode/checkXmlPrefix',
  tvshowLanguageListUrl: 'tvShow/isDoneList',
  tvShowGlobalProperties:'/tvShow/globalProperties',
  base_url: 'https://www.zee5.com',
  castCount : '/cast-count',
  movieCount : '/movie/Count',
  tvshowCount: '/tvshow/Count',
  tvshowList: '/tvshow',
  tvshowListTotal:'/tvShow/listTotal',
  videoCount : '/video/Count',
  collectionCount : 'collection/Count',
  movieAction: "/movie/action",
  countryGroup: "master/Country",
  castLanguage: "/cast/translation",
  redirectionType :"RedirectionType",
  sefUrl :"/movies/details",
  TvShowLicense :"tvShow/license",
  videoSefUrl :"/videos/details",
  tvShowSefUrl :"/tvshow/details",
  seasonSefUrl :"/season/details",
  episodeSefUrl :"/episode/details",
  transcodingList: "transcoding-list",
  transcodingHistoryList: "/transcoding-history-list",
  transcoding: "transcoding",
  videoLicense : "/video/licence",
  videoEdit :"/video/edit/",
  episodeCount:'/episode/Count',
  seoDomainName :"Domain Name: https://www.zee5.com",


  video: {
    video: "/video/video",
    videoList: "/video",
    mapContent: "/video/mapContent",
    relatedContent: '/video/relatedContent',
    relatedContentRearrange: '/video/relatedContent/rearrange',
    rearrangeContent: '/video/rearrangeContent',
    count : '/video/Count',
    mapContentRearrange: '/video/mapContent/rearrange',
    action: '/video/action',
    licenseCountries: '/video/licenseCountries',
    languageListStatus: '/video/languageListStatus',
    videoProperties: '/videoProperties',
    collectionAssignment: '/video/collectionAssign',
    videoSeo :"/video/seo",
    translation: '/video/translation',
    translationCastCrew: '/video/castTranslation',
    videoControlField: '/video/properties/controlFields',
    videoLicenseAudit :"/licenceAuditLogs",
  },
  videoImageSet: '/video/imageSet',
  videoCastAndCrew: '/video/castAndCrew',
  videoLanguageListUrl: '/video/isDoneList',
  tvShowEdit :'/tvshow/edit/',
  seasonConst :'season',
  season: {
    seasonOrder:'/season/order',
    seasonProperties: '/season/properties',
    seasonControlFields:'season/properties/controlFields',
    count: '/season/Count',
    action: '/season/action',
    licenseCountries: '/season/licenseCountries',
    languageListStatus: '/season/languageListStatus',
    castAndCrew: '/season/castAndCrew',
    collectionAssignment: '/season/collectionAssign',
    relatedContent: '/season/relatedContent',
    relatedRearrangeContent: '/season/rearrangeContent',
    seasonLicense :'/season/license',
    imageSet:'/season/imageSet',
    translation: '/season/translation',
    translationCastCrew: '/season/castTranslation',
    globalTranslation: '/season/globalTranslation',
    seo: '/season/seo',
    global: '/season/global',
    seoGlobal: '/season/seoGlobal',
    collectionList :'tvShow/collectionList',
    tvShowEpisodeStatus: 'season/tvShowEpisodeStatus'
  },
  episode: {
    episodeOrder:'/episode/order',
    action: '/episode/action',
    licenseDetails: '/episode/licenseDetails',
    castAndCrew: '/episode/castAndCrew',
    collectionAssignment: '/episode/collectionAssign',
    relatedContent: '/episode/relatedContent',
    relatedRearrangeContent: '/episode/rearrangeContent',
    translation: '/episode/translation',
    translationCastCrew: '/episode/castTranslation',
    globalTranslation: '/episode/globalTranslation',
    imageSet:'/episode/imageSet',
    seo: '/episode/seo',
    episodeProperties:'/episode/properties',
    licenseCountries: '/episode/licenseCountries',
    languageListStatus: '/episode/languageListStatus',
    license:'episode/license',
    episodeTemplate :'/episode/template',
    tvshowSeasonStatus: '/episode/tvShowSeasonStatus',
    video :'/episode/video',
    episodeControlFields: 'episode/properties/controlFields'
  },
  seasonLanguageListUrl: '/season/isDoneList',
  episodeLanguageListUrl: '/episode/isDoneList',
  templateTranslation: '/template/translation',
  placeholderSeason: '/placeHolder/season',
  bulkUpdate:{
    bulkOpsIndexUpdate: '/updateIndex',
    bulkOpsIndexUpdatePublish: '/bulkPublish',
    history: 'history?operation=',
    tvShowExport:'tvShowexport',
    tvShowExportStatus:'export-status',
    importTvShow:'importTvShow',
    importMovie:'/movie/import',
    importVideo:'/video/import',
    validate:'/validate',
    validateUpdateVideo: '/update-video-section/validate',
    importUpdateVideo: '/update-video-section/import',
    publishUpdateVideo: '/bulkPublish',
    episodeExport:'episodes/export',
    importEpisode:'episodes/import',
    movieExport:'/movie/export',
    videoExport:'/video/export',
    episodeUpdate: 'episodes/update',
    moviePublish:'/movie/publish',
    videoPublish: '/video/publish',
    tvshowPublish: 'importTvShow/publish',
    episodePublish: 'episodes/publish',
    bulkOperations:'/bulkOperations/publish',
    image: 'image',
    imagePublish: '/image/publish',
    imageUpload: '/image/upload',
    jobIdHistory:'bulkupdate/dashboard',
    bulkOpsPlaceholder:'/episode/placeholder/validate',
    updatePlaceholder:'/episodes/placeholder'
  }
};

// Default to dev if not set
const config = process.env.REACT_APP_STAGE === "prod"
  ? prod
  : (process.env.REACT_APP_STAGE === "uat" ? uat : dev);
export default {
  // Add common config values here
  MAX_ATTACHMENT_SIZE: 5000000,
  timeout: 60 * 60 * 1000,
  ...config
};