name: cd-uat-azure
on:
  workflow_dispatch:

jobs:
  infra-deploy:
    runs-on: cmsnonprodfrontendrunner
    environment: uat
    env:
      ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID_NP }}"
      ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET_NP }}"
      ARM_SUBSCRIPTION_ID: "951bb481-cd31-4ad0-add8-6914f12d4849"
      RESOURCE_GROUP_NAME: "rg-zee5-uat-ci1-cms-0001"
      STORAGE_ACCOUNT_NAME: "stzee5uatci1cms0002"
      ADFS_CLIENT_ID: 'ADFS_CLIENT_ID=79dbb777-82e3-4fe7-bbdd-bd22c7690973'
      ADFS_AUTHORITY_URL: 'ADFS_AUTHORITY_URL=https://login.microsoftonline.com/56bd48cd-f312-49e8-b6c7-7b5b926c03d6'
      LOGOUT_URL: 'LOGOUT_URL=https://ott-test.auth.ap-south-1.amazoncognito.com/logout?client_id=6ikgvb8vps2speskpqn321k993&logout_uri=https://zee5np-endpoint-hsczh4c7f9ahg3cx.z01.azurefd.net/'
      LOGINURL: 'LOGINURL=https://apim-uat.azott.in/cms/api/v1.0/user/login?env=localhost&code='
      ADFS_LOGIN_URL: 'ADFS_LOGIN_URL=https://ott-test.auth.ap-south-1.amazoncognito.com/oauth2/authorize?identity_provider=adfs&redirect_uri=https://zee5np-endpoint-hsczh4c7f9ahg3cx.z01.azurefd.net/&response_type=code&client_id=2cea9a0a-1ec3-46db-b505-b4921ee45609&scope=openid+email'																																																																			 
      BACKEND_API_URL: 'BACKEND_API_URL=https://apim-uat.azott.in/api/v1.0'
      BACKEND_API_PLACEHOLDER_URL: 'BACKEND_API_PLACEHOLDER_URL=https://apim-uat.azott.in/bulkops/api/v1.0'
      IMAGE_BASE_URL: 'IMAGE_BASE_URL=https://cms-uat-images.azott.in'

    steps:
      # Az CLI Login
      - name: Az CLI Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET_NP }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - uses: actions/checkout@v2
        with:
          path: cms-frontend
          fetch-depth: "0"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "12.10.0"

      - name: Deploy in StorageAccount
        shell: bash
        run: |
          cd cms-frontend
          touch .env
          #echo "${{ secrets.BACKEND_API_URL }}" >> .env
          #echo "${{ secrets.LOGINURL }}" >> .env
          # echo "${{ secrets.ADFS_LOGIN_URL }}" >> .env
          echo "${{ secrets.GOOGLE_LOGIN_URL }}" >> .env
          # echo "${{ secrets.LOGOUT_URL }}" >> .env
          echo "${{ secrets.ADFS_LOGOUT_URL }}" >> .env
          #echo "${{ secrets.IMAGE_BASE_URL }}" >> .env
          echo "${{ secrets.LOGGING_MAIN_URL }}" >> .env
          echo "${{ secrets.LOGGING_REPORTING_URL }}" >> .env
          echo "${{ secrets.LOGGING_KEY }}" >> .env
          #echo "${{ secrets.BACKEND_API_PLACEHOLDER_URL }}" >> .env

          echo "${{ env.ADFS_LOGIN_URL }}" >> .env
          echo "${{ env.LOGOUT_URL }}" >> .env
          echo "${{ env.ADFS_CLIENT_ID }}" >> .env
          echo "${{ env.ADFS_AUTHORITY_URL }}" >> .env
          echo "${{ env.LOGINURL }}" >> .env
          echo "${{ env.BACKEND_API_URL }}" >> .env
          echo "${{ env.BACKEND_API_PLACEHOLDER_URL }}" >> .env
          echo "${{ env.IMAGE_BASE_URL }}" >> .env
          # echo "${{ env.SAS_TOKEN_STORAGE }}" >> .env
           
          
          cat .env
          npm install
          npm run build
          az storage blob upload-batch --destination '$web' --source dist --account-name stzee5uatci1cms0002 --overwrite
          # aws cloudfront create-invalidation --distribution-id "E2DK8ZUVWS9BCN" --paths "/*" --profile default
          # az cdn endpoint purge -g <resource-group-name> --profile-name <cdn-profile-name> --name <cdn-endpoint-name> --content-paths "/*"

      - name: Az CLI Logout
        if: always()
        run: |
          az logout
